version: '2'

name: my_kafka_project

services:
  zookeeper:
    container_name: zookeeper
    image: wurstmeister/zookeeper:latest
    ports:
      - "2181:2181"
    environment:
      - ZOOKEEPER_CLIENT_PORT=2181
      - ZOOKEEPER_TICK_TIME=2000
      - ZOOKEEPER_SYNC_LIMIT=2

  kafka:
    container_name: kafka
    image: confluentinc/cp-kafka:latest
    ports:
      - "9093:9093"  # Expose the external port for Kafka clients
    expose:
      - "9092"  # Expose the internal port for Kafka brokers
    environment:
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9093  # External client can access on localhost:9093
      - KAFKA_LISTENER_SECURITY_PROTOCOL=PLAINTEXT
      - KAFKA_LISTENER_PORT=9092  # Internal port for communication within Docker network
      - KAFKA_LISTENER_NAME=PLAINTEXT
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181  # Connect to Zookeeper running in the 'zookeeper' container
      - KAFKA_LISTENER_INTER_BROKER_SECURITY_PROTOCOL=PLAINTEXT
      - KAFKA_LISTENER_NAME_INNER=INTERNAL  # Used internally between brokers (optional)
      - KAFKA_LISTENER_PORT_INNER=9092  # Internal port for inter-broker communication
      - KAFKA_DEFAULT_REPLICATION_FACTOR=1  # Set replication factor to 1 since we only have 1 broker
    depends_on:
      - zookeeper
